// <auto-generated />
using System;
using System.Collections.Generic;
using Archive.Properties;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Archive.Migrations
{
    [DbContext(typeof(ArchiveFqpContext))]
    [Migration("20260218133734_WithoutChildren")]
    partial class WithoutChildren
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.HasPostgresExtension(modelBuilder, "pg_trgm");
            NpgsqlModelBuilderExtensions.HasPostgresExtension(modelBuilder, "pgcrypto");
            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Archive.Models.Database.АккаунтПользователя", b =>
                {
                    b.Property<int>("IdПользователя")
                        .HasColumnType("integer")
                        .HasColumnName("id_пользователя");

                    b.Property<string>("Логин")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("character varying(60)")
                        .HasColumnName("логин");

                    b.Property<string>("Пароль")
                        .IsRequired()
                        .HasColumnType("character varying")
                        .HasColumnName("пароль");

                    b.PrimitiveCollection<List<int>>("Роли")
                        .IsRequired()
                        .HasColumnType("integer[]")
                        .HasColumnName("роли");

                    b.HasIndex(new[] { "IdПользователя" }, "аккаунт_пользова_id_пользователя_key")
                        .IsUnique();

                    b.ToTable("аккаунт_пользователя", (string)null);
                });

            modelBuilder.Entity("Archive.Models.Database.Атрибут", b =>
                {
                    b.Property<int>("IdАтрибута")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id_атрибута");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdАтрибута"));

                    b.Property<string>("Название")
                        .IsRequired()
                        .HasColumnType("character varying")
                        .HasColumnName("название");

                    b.HasKey("IdАтрибута")
                        .HasName("атрибут_pkey");

                    b.HasIndex(new[] { "Название" }, "атрибут_название_key")
                        .IsUnique();

                    b.ToTable("атрибут", (string)null);
                });

            modelBuilder.Entity("Archive.Models.Database.АтрибутИнститута", b =>
                {
                    b.Property<int>("IdАтрибута")
                        .HasColumnType("integer")
                        .HasColumnName("id_атрибута");

                    b.Property<int>("IdИнститута")
                        .HasColumnType("integer")
                        .HasColumnName("id_института");

                    b.Property<int?>("IdСтатусаРаботы")
                        .HasColumnType("integer")
                        .HasColumnName("id_статуса_работы");

                    b.Property<int>("IdСтруктуры")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id_структуры")
                        .HasDefaultValueSql("nextval('\"атрибут_учреждения_id_структуры_seq\"'::regclass)");

                    b.Property<int?>("IdТипаРаботы")
                        .HasColumnType("integer")
                        .HasColumnName("id_типа_работы");

                    b.HasIndex(new[] { "IdИнститута", "IdАтрибута", "IdСтатусаРаботы", "IdТипаРаботы" }, "атрибут_института_атрибут_key")
                        .IsUnique();

                    b.ToTable("атрибут_института", (string)null);
                });

            modelBuilder.Entity("Archive.Models.Database.АтрибутКафедры", b =>
                {
                    b.Property<int>("IdАтрибута")
                        .HasColumnType("integer")
                        .HasColumnName("id_атрибута");

                    b.Property<int>("IdКафедры")
                        .HasColumnType("integer")
                        .HasColumnName("id_кафедры");

                    b.Property<int?>("IdСтатусаРаботы")
                        .HasColumnType("integer")
                        .HasColumnName("id_статуса_работы");

                    b.Property<int>("IdСтруктуры")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id_структуры")
                        .HasDefaultValueSql("nextval('\"атрибут_учреждения_id_структуры_seq\"'::regclass)");

                    b.Property<int?>("IdТипаРаботы")
                        .HasColumnType("integer")
                        .HasColumnName("id_типа_работы");

                    b.HasIndex(new[] { "IdКафедры", "IdАтрибута", "IdСтатусаРаботы", "IdТипаРаботы" }, "атрибут_кафедры_атрибут_key")
                        .IsUnique();

                    b.ToTable("атрибут_кафедры", (string)null);
                });

            modelBuilder.Entity("Archive.Models.Database.АтрибутНаправления", b =>
                {
                    b.Property<int>("IdАтрибута")
                        .HasColumnType("integer")
                        .HasColumnName("id_атрибута");

                    b.Property<int>("IdНаправления")
                        .HasColumnType("integer")
                        .HasColumnName("id_направления");

                    b.Property<int?>("IdСтатусаРаботы")
                        .HasColumnType("integer")
                        .HasColumnName("id_статуса_работы");

                    b.Property<int>("IdСтруктуры")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id_структуры")
                        .HasDefaultValueSql("nextval('\"атрибут_учреждения_id_структуры_seq\"'::regclass)");

                    b.Property<int?>("IdТипаРаботы")
                        .HasColumnType("integer")
                        .HasColumnName("id_типа_работы");

                    b.HasIndex(new[] { "IdНаправления", "IdАтрибута", "IdСтатусаРаботы", "IdТипаРаботы" }, "атрибут_направления_атрибут_key")
                        .IsUnique();

                    b.ToTable("атрибут_направления", (string)null);
                });

            modelBuilder.Entity("Archive.Models.Database.АтрибутПрофиля", b =>
                {
                    b.Property<int>("IdАтрибута")
                        .HasColumnType("integer")
                        .HasColumnName("id_атрибута");

                    b.Property<int>("IdПрофиля")
                        .HasColumnType("integer")
                        .HasColumnName("id_профиля");

                    b.Property<int?>("IdСтатусаРаботы")
                        .HasColumnType("integer")
                        .HasColumnName("id_статуса_работы");

                    b.Property<int>("IdСтруктуры")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id_структуры")
                        .HasDefaultValueSql("nextval('\"атрибут_учреждения_id_структуры_seq\"'::regclass)");

                    b.Property<int?>("IdТипаРаботы")
                        .HasColumnType("integer")
                        .HasColumnName("id_типа_работы");

                    b.HasIndex(new[] { "IdПрофиля", "IdАтрибута", "IdСтатусаРаботы", "IdТипаРаботы" }, "атрибут_профиля_атрибут_key")
                        .IsUnique();

                    b.ToTable("атрибут_профиля", (string)null);
                });

            modelBuilder.Entity("Archive.Models.Database.АтрибутУчреждения", b =>
                {
                    b.Property<int>("IdСтруктуры")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id_структуры");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdСтруктуры"));

                    b.Property<int>("IdАтрибута")
                        .HasColumnType("integer")
                        .HasColumnName("id_атрибута");

                    b.Property<int?>("IdСтатусаРаботы")
                        .HasColumnType("integer")
                        .HasColumnName("id_статуса_работы");

                    b.Property<int?>("IdТипаРаботы")
                        .HasColumnType("integer")
                        .HasColumnName("id_типа_работы");

                    b.HasKey("IdСтруктуры")
                        .HasName("атрибут_учреждения_pkey");

                    b.HasIndex("IdСтатусаРаботы");

                    b.HasIndex("IdТипаРаботы");

                    b.HasIndex(new[] { "IdАтрибута", "IdСтатусаРаботы", "IdТипаРаботы" }, "атрибут_учреждения_атрибут_key")
                        .IsUnique();

                    b.ToTable("атрибут_учреждения", (string)null);
                });

            modelBuilder.Entity("Archive.Models.Database.ВыдачаРаботы", b =>
                {
                    b.Property<int>("IdВыдачи")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id_выдачи");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdВыдачи"));

                    b.Property<int>("IdПользователя")
                        .HasColumnType("integer")
                        .HasColumnName("id_пользователя");

                    b.Property<int>("IdРаботы")
                        .HasColumnType("integer")
                        .HasColumnName("id_работы");

                    b.Property<DateTime>("ДатаВозврПоЗаявл")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("дата_возвр_по_заявл");

                    b.Property<DateTime?>("ДатаВозврПоФакту")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("дата_возвр_по_факту");

                    b.Property<DateTime?>("ДатаОтвета")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("дата_ответа");

                    b.Property<DateTime>("ДатаПоступления")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("дата_поступления")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("Ответ")
                        .HasColumnType("character varying")
                        .HasColumnName("ответ");

                    b.Property<string>("Цель")
                        .IsRequired()
                        .HasColumnType("character varying")
                        .HasColumnName("цель");

                    b.HasKey("IdВыдачи")
                        .HasName("выдача_работы_pkey");

                    b.HasIndex("IdПользователя");

                    b.HasIndex("IdРаботы");

                    b.ToTable("выдача_работы", (string)null);
                });

            modelBuilder.Entity("Archive.Models.Database.ДанныеПоАтриб", b =>
                {
                    b.Property<int>("IdРаботы")
                        .HasColumnType("integer")
                        .HasColumnName("id_работы");

                    b.Property<int>("IdСтруктуры")
                        .HasColumnType("integer")
                        .HasColumnName("id_структуры");

                    b.Property<string>("Данные")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text")
                        .HasColumnName("данные")
                        .HasDefaultValueSql("'Ожидание поиска...'::text");

                    b.HasIndex(new[] { "IdРаботы", "IdСтруктуры" }, "данные_по_атриб_атрибут_key")
                        .IsUnique();

                    b.ToTable("данные_по_атриб", (string)null);
                });

            modelBuilder.Entity("Archive.Models.Database.Должность", b =>
                {
                    b.Property<int>("IdДолжности")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id_должности");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdДолжности"));

                    b.Property<string>("Название")
                        .IsRequired()
                        .HasColumnType("character varying")
                        .HasColumnName("название");

                    b.HasKey("IdДолжности")
                        .HasName("должность_pkey");

                    b.HasIndex(new[] { "Название" }, "должность_название_key")
                        .IsUnique();

                    b.ToTable("должность", (string)null);
                });

            modelBuilder.Entity("Archive.Models.Database.ЖурналДействий", b =>
                {
                    b.Property<DateTime?>("Время")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("время")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("Запрос")
                        .HasColumnType("text")
                        .HasColumnName("запрос");

                    b.Property<string>("НовыеДанные")
                        .HasColumnType("character varying")
                        .HasColumnName("новые_данные");

                    b.Property<string>("Операция")
                        .IsRequired()
                        .HasColumnType("character varying")
                        .HasColumnName("операция");

                    b.Property<string>("СтарыеДанные")
                        .HasColumnType("character varying")
                        .HasColumnName("старые_данные");

                    b.Property<string>("Схема")
                        .IsRequired()
                        .HasColumnType("character varying")
                        .HasColumnName("схема");

                    b.Property<string>("Таблица")
                        .IsRequired()
                        .HasColumnType("character varying")
                        .HasColumnName("таблица");

                    b.ToTable("журнал_действий", (string)null);
                });

            modelBuilder.Entity("Archive.Models.Database.Институт", b =>
                {
                    b.Property<int>("IdИнститута")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id_института");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdИнститута"));

                    b.Property<string>("Название")
                        .IsRequired()
                        .HasColumnType("character varying")
                        .HasColumnName("название");

                    b.HasKey("IdИнститута")
                        .HasName("институт_pkey");

                    b.HasIndex(new[] { "Название" }, "институт_название_key")
                        .IsUnique();

                    b.ToTable("институт", (string)null);
                });

            modelBuilder.Entity("Archive.Models.Database.Кафедра", b =>
                {
                    b.Property<int>("IdКафедры")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id_кафедры");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdКафедры"));

                    b.Property<int>("IdИнститута")
                        .HasColumnType("integer")
                        .HasColumnName("id_института");

                    b.Property<int?>("IdУгсн")
                        .HasColumnType("integer")
                        .HasColumnName("id_угсн");

                    b.Property<string>("Название")
                        .IsRequired()
                        .HasColumnType("character varying")
                        .HasColumnName("название");

                    b.HasKey("IdКафедры")
                        .HasName("кафедра_pkey");

                    b.HasIndex("IdИнститута");

                    b.HasIndex("IdУгсн");

                    b.HasIndex(new[] { "Название", "IdУгсн" }, "кафедра_кафедра_key")
                        .IsUnique();

                    b.ToTable("кафедра", (string)null);
                });

            modelBuilder.Entity("Archive.Models.Database.Направление", b =>
                {
                    b.Property<int>("IdНаправления")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id_направления");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdНаправления"));

                    b.Property<int>("IdКафедры")
                        .HasColumnType("integer")
                        .HasColumnName("id_кафедры");

                    b.Property<string>("Название")
                        .IsRequired()
                        .HasColumnType("character varying")
                        .HasColumnName("название");

                    b.HasKey("IdНаправления")
                        .HasName("направление_pkey");

                    b.HasIndex("IdКафедры");

                    b.HasIndex(new[] { "Название", "IdКафедры" }, "направление_направление_key")
                        .IsUnique();

                    b.ToTable("направление", (string)null);
                });

            modelBuilder.Entity("Archive.Models.Database.ОценкаПреподавателя", b =>
                {
                    b.Property<int>("IdПреподавателя")
                        .HasColumnType("integer")
                        .HasColumnName("id_преподавателя");

                    b.Property<int>("IdРаботы")
                        .HasColumnType("integer")
                        .HasColumnName("id_работы");

                    b.Property<string>("Отзыв")
                        .HasColumnType("text")
                        .HasColumnName("отзыв");

                    b.Property<int>("Оценка")
                        .HasColumnType("integer")
                        .HasColumnName("оценка");

                    b.HasIndex("IdПреподавателя");

                    b.HasIndex("IdРаботы");

                    b.ToTable("оценка_преподавателя", (string)null);
                });

            modelBuilder.Entity("Archive.Models.Database.Пользователь", b =>
                {
                    b.Property<int>("IdПользователя")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id_пользователя");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdПользователя"));

                    b.Property<string>("Email")
                        .HasColumnType("character varying")
                        .HasColumnName("email");

                    b.Property<string>("Имя")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("имя");

                    b.Property<string>("Отчество")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("отчество");

                    b.Property<string>("Фамилия")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("фамилия");

                    b.HasKey("IdПользователя")
                        .HasName("пользователь_pkey");

                    b.HasIndex(new[] { "Email" }, "пользователь_email_key")
                        .IsUnique();

                    b.ToTable("пользователь", (string)null);
                });

            modelBuilder.Entity("Archive.Models.Database.Преподаватель", b =>
                {
                    b.Property<int>("IdПреподавателя")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id_преподавателя");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdПреподавателя"));

                    b.Property<int>("IdДолжности")
                        .HasColumnType("integer")
                        .HasColumnName("id_должности");

                    b.Property<int>("IdИнститута")
                        .HasColumnType("integer")
                        .HasColumnName("id_института");

                    b.Property<int>("IdКафедры")
                        .HasColumnType("integer")
                        .HasColumnName("id_кафедры");

                    b.Property<int>("IdПользователя")
                        .HasColumnType("integer")
                        .HasColumnName("id_пользователя");

                    b.HasKey("IdПреподавателя")
                        .HasName("преподаватель_pkey");

                    b.HasIndex("IdДолжности");

                    b.HasIndex("IdИнститута");

                    b.HasIndex("IdКафедры");

                    b.HasIndex("IdПользователя");

                    b.ToTable("преподаватель", (string)null);
                });

            modelBuilder.Entity("Archive.Models.Database.Профиль", b =>
                {
                    b.Property<int>("IdПрофиля")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id_профиля");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdПрофиля"));

                    b.Property<int>("IdНаправления")
                        .HasColumnType("integer")
                        .HasColumnName("id_направления");

                    b.Property<string>("Название")
                        .IsRequired()
                        .HasColumnType("character varying")
                        .HasColumnName("название");

                    b.HasKey("IdПрофиля")
                        .HasName("профиль_pkey");

                    b.HasIndex("IdНаправления");

                    b.HasIndex(new[] { "Название", "IdНаправления" }, "профиль_профиль_key")
                        .IsUnique();

                    b.ToTable("профиль", (string)null);
                });

            modelBuilder.Entity("Archive.Models.Database.Работа", b =>
                {
                    b.Property<int>("IdРаботы")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id_работы");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdРаботы"));

                    b.Property<int>("IdПреподавателя")
                        .HasColumnType("integer")
                        .HasColumnName("id_преподавателя");

                    b.Property<int>("IdСтатусаРаботы")
                        .HasColumnType("integer")
                        .HasColumnName("id_статуса_работы");

                    b.Property<int>("IdСтудента")
                        .HasColumnType("integer")
                        .HasColumnName("id_студента");

                    b.Property<int>("IdТипаРаботы")
                        .HasColumnType("integer")
                        .HasColumnName("id_типа_работы");

                    b.Property<DateTime>("ДатаДобавления")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("дата_добавления")
                        .HasDefaultValueSql("now()");

                    b.Property<DateTime?>("ДатаИзменения")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("дата_изменения");

                    b.Property<int?>("КоличСтраниц")
                        .HasColumnType("integer")
                        .HasColumnName("колич_страниц");

                    b.Property<string>("Местоположение")
                        .HasColumnType("character varying")
                        .HasColumnName("местоположение");

                    b.Property<string>("Тема")
                        .IsRequired()
                        .HasColumnType("character varying")
                        .HasColumnName("тема");

                    b.Property<string>("Эцп")
                        .HasColumnType("character varying")
                        .HasColumnName("ЭЦП");

                    b.HasKey("IdРаботы")
                        .HasName("работа_pkey");

                    b.HasIndex("IdПреподавателя");

                    b.HasIndex("IdСтатусаРаботы");

                    b.HasIndex("IdТипаРаботы");

                    b.HasIndex(new[] { "Эцп" }, "работа_ЭЦП_key")
                        .IsUnique();

                    b.HasIndex(new[] { "Местоположение" }, "работа_местоположение_key")
                        .IsUnique();

                    b.HasIndex(new[] { "IdСтудента", "Тема" }, "работа_работа_студента_key")
                        .IsUnique();

                    b.HasIndex(new[] { "Тема", "IdТипаРаботы" }, "работа_работа_студентов_key")
                        .IsUnique();

                    b.ToTable("работа", (string)null);
                });

            modelBuilder.Entity("Archive.Models.Database.РольПользователя", b =>
                {
                    b.Property<int>("IdРоли")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id_роли");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdРоли"));

                    b.Property<string>("Название")
                        .IsRequired()
                        .HasColumnType("character varying")
                        .HasColumnName("название");

                    b.HasKey("IdРоли")
                        .HasName("роль_пользователя_pkey");

                    b.HasIndex(new[] { "Название" }, "роль_пользователя_название_key")
                        .IsUnique();

                    b.ToTable("роль_пользователя", (string)null);
                });

            modelBuilder.Entity("Archive.Models.Database.СтатусРаботы", b =>
                {
                    b.Property<int>("IdСтатусаРаботы")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id_статуса_работы");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdСтатусаРаботы"));

                    b.Property<string>("Название")
                        .IsRequired()
                        .HasColumnType("character varying")
                        .HasColumnName("название");

                    b.HasKey("IdСтатусаРаботы")
                        .HasName("статус_работы_pkey");

                    b.HasIndex(new[] { "Название" }, "статус_работы_название_key")
                        .IsUnique();

                    b.ToTable("статус_работы", (string)null);
                });

            modelBuilder.Entity("Archive.Models.Database.Студент", b =>
                {
                    b.Property<int>("IdСтудента")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id_студента");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdСтудента"));

                    b.Property<int>("IdИнститута")
                        .HasColumnType("integer")
                        .HasColumnName("id_института");

                    b.Property<int>("IdНаправления")
                        .HasColumnType("integer")
                        .HasColumnName("id_направления");

                    b.Property<int>("IdПользователя")
                        .HasColumnType("integer")
                        .HasColumnName("id_пользователя");

                    b.Property<int?>("IdПрофиля")
                        .HasColumnType("integer")
                        .HasColumnName("id_профиля");

                    b.Property<int>("IdУровняОбразования")
                        .HasColumnType("integer")
                        .HasColumnName("id_уровня_образования");

                    b.Property<int>("IdФормыОбразования")
                        .HasColumnType("integer")
                        .HasColumnName("id_формы_образования");

                    b.Property<int>("ГодОкончания")
                        .HasColumnType("integer")
                        .HasColumnName("год_окончания");

                    b.HasKey("IdСтудента")
                        .HasName("студент_pkey");

                    b.HasIndex("IdИнститута");

                    b.HasIndex("IdНаправления");

                    b.HasIndex("IdПрофиля");

                    b.HasIndex("IdУровняОбразования");

                    b.HasIndex("IdФормыОбразования");

                    b.HasIndex(new[] { "IdПользователя", "IdИнститута", "IdНаправления", "IdПрофиля", "IdФормыОбразования", "IdУровняОбразования", "ГодОкончания" }, "студент_студент_key")
                        .IsUnique();

                    b.ToTable("студент", (string)null);
                });

            modelBuilder.Entity("Archive.Models.Database.ТипРаботы", b =>
                {
                    b.Property<int>("IdТипаРаботы")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id_типа_работы");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdТипаРаботы"));

                    b.Property<string>("Название")
                        .IsRequired()
                        .HasColumnType("character varying")
                        .HasColumnName("название");

                    b.HasKey("IdТипаРаботы")
                        .HasName("тип_работы_pkey");

                    b.HasIndex(new[] { "Название" }, "тип_работы_название_key")
                        .IsUnique();

                    b.ToTable("тип_работы", (string)null);
                });

            modelBuilder.Entity("Archive.Models.Database.Угсн", b =>
                {
                    b.Property<int>("IdУгсн")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id_угсн");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdУгсн"));

                    b.Property<int>("IdУгснСтандарта")
                        .HasColumnType("integer")
                        .HasColumnName("id_угсн_стандарта");

                    b.Property<string>("Название")
                        .IsRequired()
                        .HasColumnType("character varying")
                        .HasColumnName("название");

                    b.HasKey("IdУгсн")
                        .HasName("угсн_pkey");

                    b.HasIndex("IdУгснСтандарта");

                    b.HasIndex(new[] { "Название" }, "угсн_название_key")
                        .IsUnique();

                    b.ToTable("угсн", null, t =>
                        {
                            t.HasComment("угсн");
                        });
                });

            modelBuilder.Entity("Archive.Models.Database.УгснСтандарт", b =>
                {
                    b.Property<int>("IdУгснСтандарта")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id_угсн_стандарта");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdУгснСтандарта"));

                    b.Property<string>("Название")
                        .IsRequired()
                        .HasColumnType("character varying")
                        .HasColumnName("название");

                    b.HasKey("IdУгснСтандарта")
                        .HasName("угсн_стандарт_pkey");

                    b.HasIndex(new[] { "Название" }, "угсн_стандарт_название_key")
                        .IsUnique();

                    b.ToTable("угсн_стандарт", null, t =>
                        {
                            t.HasComment("Стандарт угсн");
                        });
                });

            modelBuilder.Entity("Archive.Models.Database.УровеньОбразования", b =>
                {
                    b.Property<int>("IdУровняОбразования")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id_уровня_образования");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdУровняОбразования"));

                    b.Property<string>("Название")
                        .IsRequired()
                        .HasColumnType("character varying")
                        .HasColumnName("название");

                    b.HasKey("IdУровняОбразования")
                        .HasName("уровень_образования_pkey");

                    b.HasIndex(new[] { "Название" }, "уровень_образования_название_key")
                        .IsUnique();

                    b.ToTable("уровень_образования", (string)null);
                });

            modelBuilder.Entity("Archive.Models.Database.ФормаОбразования", b =>
                {
                    b.Property<int>("IdФормыОбразования")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id_формы_образования");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdФормыОбразования"));

                    b.Property<string>("Название")
                        .IsRequired()
                        .HasColumnType("character varying")
                        .HasColumnName("название");

                    b.HasKey("IdФормыОбразования")
                        .HasName("форма_образования_pkey");

                    b.HasIndex(new[] { "Название" }, "форма_образования_название_key")
                        .IsUnique();

                    b.ToTable("форма_образования", (string)null);
                });

            modelBuilder.Entity("Archive.Models.Database.АккаунтПользователя", b =>
                {
                    b.HasOne("Archive.Models.Database.Пользователь", "IdПользователяNavigation")
                        .WithOne()
                        .HasForeignKey("Archive.Models.Database.АккаунтПользователя", "IdПользователя")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("аккаунт_пользов_id_пользователя_fkey");

                    b.Navigation("IdПользователяNavigation");
                });

            modelBuilder.Entity("Archive.Models.Database.АтрибутИнститута", b =>
                {
                    b.HasOne("Archive.Models.Database.Институт", "IdИнститутаNavigation")
                        .WithMany()
                        .HasForeignKey("IdИнститута")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("атрибут_института_id_института_fkey");

                    b.Navigation("IdИнститутаNavigation");
                });

            modelBuilder.Entity("Archive.Models.Database.АтрибутКафедры", b =>
                {
                    b.HasOne("Archive.Models.Database.Кафедра", "IdКафедрыNavigation")
                        .WithMany()
                        .HasForeignKey("IdКафедры")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("атрибут_кафедры_id_кафедры_fkey");

                    b.Navigation("IdКафедрыNavigation");
                });

            modelBuilder.Entity("Archive.Models.Database.АтрибутНаправления", b =>
                {
                    b.HasOne("Archive.Models.Database.Направление", "IdНаправленияNavigation")
                        .WithMany()
                        .HasForeignKey("IdНаправления")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("атрибут_направле_id_направления_fkey");

                    b.Navigation("IdНаправленияNavigation");
                });

            modelBuilder.Entity("Archive.Models.Database.АтрибутПрофиля", b =>
                {
                    b.HasOne("Archive.Models.Database.Профиль", "IdПрофиляNavigation")
                        .WithMany()
                        .HasForeignKey("IdПрофиля")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("атрибут_профиля_id_профиля_fkey");

                    b.Navigation("IdПрофиляNavigation");
                });

            modelBuilder.Entity("Archive.Models.Database.АтрибутУчреждения", b =>
                {
                    b.HasOne("Archive.Models.Database.Атрибут", "IdАтрибутаNavigation")
                        .WithMany("АтрибутУчрежденияs")
                        .HasForeignKey("IdАтрибута")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("атрибут_учреждения_id_атрибута_fkey");

                    b.HasOne("Archive.Models.Database.СтатусРаботы", "IdСтатусаРаботыNavigation")
                        .WithMany("АтрибутУчрежденияs")
                        .HasForeignKey("IdСтатусаРаботы")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("атрибут_учрежде_id_статуса_работ_fkey");

                    b.HasOne("Archive.Models.Database.ТипРаботы", "IdТипаРаботыNavigation")
                        .WithMany("АтрибутУчрежденияs")
                        .HasForeignKey("IdТипаРаботы")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("атрибут_учреждени_id_типа_работы_fkey");

                    b.Navigation("IdАтрибутаNavigation");

                    b.Navigation("IdСтатусаРаботыNavigation");

                    b.Navigation("IdТипаРаботыNavigation");
                });

            modelBuilder.Entity("Archive.Models.Database.ВыдачаРаботы", b =>
                {
                    b.HasOne("Archive.Models.Database.Пользователь", "IdПользователяNavigation")
                        .WithMany("ВыдачаРаботыs")
                        .HasForeignKey("IdПользователя")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("выдача_работы_id_пользователя_fkey");

                    b.HasOne("Archive.Models.Database.Работа", "IdРаботыNavigation")
                        .WithMany("ВыдачаРаботыs")
                        .HasForeignKey("IdРаботы")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("выдача_работы_id_работы_fkey");

                    b.Navigation("IdПользователяNavigation");

                    b.Navigation("IdРаботыNavigation");
                });

            modelBuilder.Entity("Archive.Models.Database.ДанныеПоАтриб", b =>
                {
                    b.HasOne("Archive.Models.Database.Работа", "IdРаботыNavigation")
                        .WithMany()
                        .HasForeignKey("IdРаботы")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("данные_по_атриб_id_работы_fkey");

                    b.Navigation("IdРаботыNavigation");
                });

            modelBuilder.Entity("Archive.Models.Database.Кафедра", b =>
                {
                    b.HasOne("Archive.Models.Database.Институт", "IdИнститутаNavigation")
                        .WithMany("Кафедраs")
                        .HasForeignKey("IdИнститута")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("кафедра_id_института_fkey");

                    b.HasOne("Archive.Models.Database.Угсн", "IdУгснNavigation")
                        .WithMany("Кафедраs")
                        .HasForeignKey("IdУгсн")
                        .HasConstraintName("кафедра_id_угсн_fkey");

                    b.Navigation("IdИнститутаNavigation");

                    b.Navigation("IdУгснNavigation");
                });

            modelBuilder.Entity("Archive.Models.Database.Направление", b =>
                {
                    b.HasOne("Archive.Models.Database.Кафедра", "IdКафедрыNavigation")
                        .WithMany("Направлениеs")
                        .HasForeignKey("IdКафедры")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("направление_id_кафедры_fkey");

                    b.Navigation("IdКафедрыNavigation");
                });

            modelBuilder.Entity("Archive.Models.Database.ОценкаПреподавателя", b =>
                {
                    b.HasOne("Archive.Models.Database.Преподаватель", "IdПреподавателяNavigation")
                        .WithMany()
                        .HasForeignKey("IdПреподавателя")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("оценка_преподав_id_преподавател_fkey");

                    b.HasOne("Archive.Models.Database.Работа", "IdРаботыNavigation")
                        .WithMany()
                        .HasForeignKey("IdРаботы")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("оценка_преподавателя_id_работы_fkey");

                    b.Navigation("IdПреподавателяNavigation");

                    b.Navigation("IdРаботыNavigation");
                });

            modelBuilder.Entity("Archive.Models.Database.Преподаватель", b =>
                {
                    b.HasOne("Archive.Models.Database.Должность", "IdДолжностиNavigation")
                        .WithMany("Преподавательs")
                        .HasForeignKey("IdДолжности")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("преподаватель_id_должности_fkey");

                    b.HasOne("Archive.Models.Database.Институт", "IdИнститутаNavigation")
                        .WithMany("Преподавательs")
                        .HasForeignKey("IdИнститута")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("преподаватель_id_института_fkey");

                    b.HasOne("Archive.Models.Database.Кафедра", "IdКафедрыNavigation")
                        .WithMany("Преподавательs")
                        .HasForeignKey("IdКафедры")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("преподаватель_id_кафедры_fkey");

                    b.HasOne("Archive.Models.Database.Пользователь", "IdПользователяNavigation")
                        .WithMany("Преподавательs")
                        .HasForeignKey("IdПользователя")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("преподаватель_id_пользователя_fkey");

                    b.Navigation("IdДолжностиNavigation");

                    b.Navigation("IdИнститутаNavigation");

                    b.Navigation("IdКафедрыNavigation");

                    b.Navigation("IdПользователяNavigation");
                });

            modelBuilder.Entity("Archive.Models.Database.Профиль", b =>
                {
                    b.HasOne("Archive.Models.Database.Направление", "IdНаправленияNavigation")
                        .WithMany("Профильs")
                        .HasForeignKey("IdНаправления")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("профиль_id_направления_fkey");

                    b.Navigation("IdНаправленияNavigation");
                });

            modelBuilder.Entity("Archive.Models.Database.Работа", b =>
                {
                    b.HasOne("Archive.Models.Database.Преподаватель", "IdПреподавателяNavigation")
                        .WithMany("Работаs")
                        .HasForeignKey("IdПреподавателя")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("работа_id_преподавателя_fkey");

                    b.HasOne("Archive.Models.Database.СтатусРаботы", "IdСтатусаРаботыNavigation")
                        .WithMany("Работаs")
                        .HasForeignKey("IdСтатусаРаботы")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("работа_id_статуса_работы_fkey");

                    b.HasOne("Archive.Models.Database.Студент", "IdСтудентаNavigation")
                        .WithMany("Работаs")
                        .HasForeignKey("IdСтудента")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("работа_id_студента_fkey");

                    b.HasOne("Archive.Models.Database.ТипРаботы", "IdТипаРаботыNavigation")
                        .WithMany("Работаs")
                        .HasForeignKey("IdТипаРаботы")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("работа_id_типа_работы_fkey");

                    b.Navigation("IdПреподавателяNavigation");

                    b.Navigation("IdСтатусаРаботыNavigation");

                    b.Navigation("IdСтудентаNavigation");

                    b.Navigation("IdТипаРаботыNavigation");
                });

            modelBuilder.Entity("Archive.Models.Database.Студент", b =>
                {
                    b.HasOne("Archive.Models.Database.Институт", "IdИнститутаNavigation")
                        .WithMany("Студентs")
                        .HasForeignKey("IdИнститута")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("студент_id_института_fkey");

                    b.HasOne("Archive.Models.Database.Направление", "IdНаправленияNavigation")
                        .WithMany("Студентs")
                        .HasForeignKey("IdНаправления")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("студент_id_направления_fkey");

                    b.HasOne("Archive.Models.Database.Пользователь", "IdПользователяNavigation")
                        .WithMany("Студентs")
                        .HasForeignKey("IdПользователя")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("студент_id_пользователя_fkey");

                    b.HasOne("Archive.Models.Database.Профиль", "IdПрофиляNavigation")
                        .WithMany("Студентs")
                        .HasForeignKey("IdПрофиля")
                        .HasConstraintName("студент_id_профиля_fkey");

                    b.HasOne("Archive.Models.Database.УровеньОбразования", "IdУровняОбразованияNavigation")
                        .WithMany("Студентs")
                        .HasForeignKey("IdУровняОбразования")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("студент_id_уровня_образования_fkey");

                    b.HasOne("Archive.Models.Database.ФормаОбразования", "IdФормыОбразованияNavigation")
                        .WithMany("Студентs")
                        .HasForeignKey("IdФормыОбразования")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("студент_id_формы_образования_fkey");

                    b.Navigation("IdИнститутаNavigation");

                    b.Navigation("IdНаправленияNavigation");

                    b.Navigation("IdПользователяNavigation");

                    b.Navigation("IdПрофиляNavigation");

                    b.Navigation("IdУровняОбразованияNavigation");

                    b.Navigation("IdФормыОбразованияNavigation");
                });

            modelBuilder.Entity("Archive.Models.Database.Угсн", b =>
                {
                    b.HasOne("Archive.Models.Database.УгснСтандарт", "IdУгснСтандартаNavigation")
                        .WithMany("Угснs")
                        .HasForeignKey("IdУгснСтандарта")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("угсн_id_угсн_стандарта_fkey");

                    b.Navigation("IdУгснСтандартаNavigation");
                });

            modelBuilder.Entity("Archive.Models.Database.Атрибут", b =>
                {
                    b.Navigation("АтрибутУчрежденияs");
                });

            modelBuilder.Entity("Archive.Models.Database.Должность", b =>
                {
                    b.Navigation("Преподавательs");
                });

            modelBuilder.Entity("Archive.Models.Database.Институт", b =>
                {
                    b.Navigation("Кафедраs");

                    b.Navigation("Преподавательs");

                    b.Navigation("Студентs");
                });

            modelBuilder.Entity("Archive.Models.Database.Кафедра", b =>
                {
                    b.Navigation("Направлениеs");

                    b.Navigation("Преподавательs");
                });

            modelBuilder.Entity("Archive.Models.Database.Направление", b =>
                {
                    b.Navigation("Профильs");

                    b.Navigation("Студентs");
                });

            modelBuilder.Entity("Archive.Models.Database.Пользователь", b =>
                {
                    b.Navigation("ВыдачаРаботыs");

                    b.Navigation("Преподавательs");

                    b.Navigation("Студентs");
                });

            modelBuilder.Entity("Archive.Models.Database.Преподаватель", b =>
                {
                    b.Navigation("Работаs");
                });

            modelBuilder.Entity("Archive.Models.Database.Профиль", b =>
                {
                    b.Navigation("Студентs");
                });

            modelBuilder.Entity("Archive.Models.Database.Работа", b =>
                {
                    b.Navigation("ВыдачаРаботыs");
                });

            modelBuilder.Entity("Archive.Models.Database.СтатусРаботы", b =>
                {
                    b.Navigation("АтрибутУчрежденияs");

                    b.Navigation("Работаs");
                });

            modelBuilder.Entity("Archive.Models.Database.Студент", b =>
                {
                    b.Navigation("Работаs");
                });

            modelBuilder.Entity("Archive.Models.Database.ТипРаботы", b =>
                {
                    b.Navigation("АтрибутУчрежденияs");

                    b.Navigation("Работаs");
                });

            modelBuilder.Entity("Archive.Models.Database.Угсн", b =>
                {
                    b.Navigation("Кафедраs");
                });

            modelBuilder.Entity("Archive.Models.Database.УгснСтандарт", b =>
                {
                    b.Navigation("Угснs");
                });

            modelBuilder.Entity("Archive.Models.Database.УровеньОбразования", b =>
                {
                    b.Navigation("Студентs");
                });

            modelBuilder.Entity("Archive.Models.Database.ФормаОбразования", b =>
                {
                    b.Navigation("Студентs");
                });
#pragma warning restore 612, 618
        }
    }
}
